apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-us-east-2
  region: us-east-2

availabilityZones: ["us-east-2a","us-east-2b","us-east-2c"]

nodeGroups:
  - name: admin-us-east-2
    desiredCapacity: 1
    privateNetworking: true
    labels:
      dedicated: admin

  - name: tidb-us-east-2a
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-2a"]
    instanceType: c5.2xlarge
    labels:
      dedicated: tidb
    taints:
      dedicated: tidb:NoSchedule
  - name: tidb-us-east-2b
    desiredCapacity: 0
    privateNetworking: true
    availabilityZones: ["us-east-2b"]
    instanceType: c5.2xlarge
    labels:
      dedicated: tidb
    taints:
      dedicated: tidb:NoSchedule
  - name: tidb-us-east-2c
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-2c"]
    instanceType: c5.2xlarge
    labels:
      dedicated: tidb
    taints:
      dedicated: tidb:NoSchedule

  - name: pd-us-east-2
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-2a"]
    instanceType: c5.xlarge
    labels:
      dedicated: pd
    taints:
      dedicated: pd:NoSchedule

  - name: tikv-east-2a
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-2a"]
    instanceType: r5b.2xlarge
    labels:
      dedicated: tikv
    taints:
      dedicated: tikv:NoSchedule
  - name: tikv-east-2c
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-2c"]
    instanceType: r5b.2xlarge
    labels:
      dedicated: tikv
    taints:
      dedicated: tikv:NoSchedule

vpc:
  cidr: 10.101.0.0/16
