apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: multi-region-test
  region: us-east-2

availabilityZones: ["us-east-2a", "us-east-2b",  "us-east-2c"]
nodeGroups:
  - name: admin
    desiredCapacity: 1
    privateNetworking: true
    labels:
      dedicated: admin

  - name: tidb-2a
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-2a"]
    instanceType: c5.2xlarge
    labels:
      dedicated: tidb
    taints:
      dedicated: tidb:NoSchedule

  - name: pd-2a
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-2a"]
    instanceType: m5.xlarge
    labels:
      dedicated: pd
    taints:
      dedicated: pd:NoSchedule


  - name: tikv-2a
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-2a"]
    instanceType: c5.2xlarge
    labels:
      dedicated: tikv
    taints:
      dedicated: tikv:NoSchedule

vpc:
  cidr: 192.168.0.0/16
  autoAllocateIPv6: false
  # disable public access to endpoint and only allow private access
  clusterEndpoints:
    publicAccess: true
    privateAccess: true 