apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: multi-region-test
  region: us-west-2

availabilityZones: ["us-west-2a", "us-west-2b",  "us-west-2c"]
nodeGroups:
  - name: admin2
    desiredCapacity: 1
    privateNetworking: true
    labels:
      dedicated: admin

  - name: tidb-3a
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-west-2a"]
    instanceType: c5.2xlarge
    labels:
      dedicated: tidb
    taints:
      dedicated: tidb:NoSchedule

  - name: pd-3a
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-west-2a"]
    instanceType: m5.xlarge
    labels:
      dedicated: pd
    taints:
      dedicated: pd:NoSchedule
      
  - name: pd-3b
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-west-2b"]
    instanceType: m5.xlarge
    labels:
      dedicated: pd
    taints:
      dedicated: pd:NoSchedule      


  - name: tikv-3a
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-west-2a"]
    instanceType: c5.2xlarge
    labels:
      dedicated: tikv
    taints:
      dedicated: tikv:NoSchedule

  - name: tikv-3b
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-west-2b"]
    instanceType: c5.2xlarge
    labels:
      dedicated: tikv
    taints:
      dedicated: tikv:NoSchedule      

vpc:
  cidr: 172.30.0.0/16
  autoAllocateIPv6: false
  # disable public access to endpoint and only allow private access
  clusterEndpoints:
    publicAccess: true
    privateAccess: true 
