apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: multi-region-test-east-1
  region: us-east-1
availabilityZones: ["us-east-1a", "us-east-1b",  "us-east-1c",  "us-east-1d"]

nodeGroups:
  - name: admin2
    desiredCapacity: 1
    privateNetworking: true
    labels:
      dedicated: admin

  - name: tidb-1a
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-1a"]
    instanceType: c5.2xlarge
    labels:
      dedicated: tidb
    taints:
      dedicated: tidb:NoSchedule

  - name: pd-1a
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-1a"]
    instanceType: m5.xlarge
    labels:
      dedicated: pd
    taints:
      dedicated: pd:NoSchedule

  - name: pd-1b
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    instanceType: m5.xlarge
    labels:
      dedicated: pd
    taints:
      dedicated: pd:NoSchedule      


  - name: tikv-1a
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-1a"]
    instanceType: c5.2xlarge
    labels:
      dedicated: tikv
    taints:
      dedicated: tikv:NoSchedule
  - name: tikv-1b
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    instanceType: c5.2xlarge
    labels:
      dedicated: tikv
    taints:
      dedicated: tikv:NoSchedule
vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: false
  # disable public access to endpoint and only allow private access
  clusterEndpoints:
    publicAccess: true
    privateAccess: true     
